# How to get storage account key 
# PREFIX=<env_prefix defined by terraform plans> 
# STORAGE_ACCOUNT_KEY=`az storage account keys list -n "${PREFIX}k8s" -g "${PREFIX}k8s" -o json --query 'keys[0].value'`
# STORAGE_ACCOUNT_NAME=`az storage account show -g "${PREFIX}k8s" -n "${PREFIX}k8s" -o json --query name`
#
# We can use following secret to mount azure_file
#  		volumes:
# 			- name: logs
#        	  azureFile: 
#         		secretName: azure-secret
#        		shareName: logs
#           	readOnly: false


apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: `echo -n "$STORAGE_ACCOUNT_NAME"| base64`
  azurestorageaccountkey: `echo -n "$STORAGE_ACCOUNT_KEY" | base64`
