apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: fluentd
spec:
    template:
        metadata:
            labels:
                app: fluentd
                logtype: archive
                secret-azure-secret: linked
            name: fluentd
        spec:
            containers:
                - image: olblak/fluentd-k8s-azure:0.7.0
                  imagePullPolicy: Always
                  name: fluentd
                  resources:
                    requests:
                        memory: "350Mi"
                        cpu: "0.1"
                    limits:
                        memory: "400Mi"
                        cpu: "0.2"
                  env:
                    - name: AZURE_WORKSPACE_ID
                      valueFrom:
                        secretKeyRef:
                            name: azure-secret
                            key: azurelogsanalyticsworkspace
                    - name: AZURE_SHARED_KEY
                      valueFrom:
                        secretKeyRef: 
                            name: azure-secret
                            key: azurelogsstorageaccountkey
                # Following variables are used by fluent-plugin-azurestorage
                # Cfr olblak/fluentd-k8s-azure:0.6.1
                    - name: AZURE_ARCHIVE_STORAGE_ACCOUNT
                      valueFrom:
                        secretKeyRef: 
                            name: azure-secret
                            key: azurearchivestorageaccount
                    - name: AZURE_ARCHIVE_STORAGE_ACCESS_KEY
                      valueFrom:
                        secretKeyRef: 
                            name: azure-secret
                            key: azurearchivestorageaccesskey
                    - name: AZURE_ARCHIVE_CONTAINER
                      valueFrom:
                        secretKeyRef: 
                            name: azure-secret
                            key: azurearchivecontainer

                  volumeMounts:
                    - name: logs
                      mountPath: /fluentd/log

                    - name: varlog
                      mountPath: /var/log
                      readOnly: true

                    - name: varlibdockercontainers
                      mountPath: /var/lib/docker/containers
                      readOnly: true

            volumes:
                - name: logs
                  azureFile: 
                    secretName: azure-secret
                    shareName: logs
                    readOnly: false

                - name: varlibdockercontainers
                  hostPath:
                      path: /var/lib/docker/containers

                - name: varlog
                  hostPath:
                      path: /var/log
