---
apiVersion: v1
kind: ReplicationController
metadata:
    name: plugins-jenkins
    labels:
        app: plugin-jenkins
        type: plugins-jenkins
        logtype: archive
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: plugins-jenkins
                type: plugins-jenkins
                logtype: archive
        spec:
            containers:
                - name: plugins-jenkins
                  image: jenkinsciinfra/plugin-site:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5000
                        protocol: TCP
                      - containerPort: 8080
                        protocol: TCP
                  env:
                      - name: REST_API_URL
                        value: "https://api.plugins.jenkins.io"
                      - name: DATA_FILE_URL
                        value: 'https://ci.jenkins.io/job/Infra/job/plugin-site-api/job/generate-data/lastSuccessfulBuild/artifact/plugins.json.gzip'

    # It seems that this pod require quite a lot of resources, so let's wait and see before defining resource limitation
