---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: plugins-jenkins
    labels:
        app: plugins-jenkins
        type: plugins-jenkins
        logtype: archive
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: plugins-jenkins
                type: plugins-jenkins
                logtype: archive
                configmap-plugins-jenking: linked
        spec:
            containers:
                - name: plugins-jenkins
                  image: jenkinsciinfra/plugin-site:latest
                  imagePullPolicy: Always
                  livenessProbe:
                      httpGet:
                          path: /labels
                          port: 8080
                          scheme: HTTP
                      initialDelaySeconds: 30
                      timeoutSeconds: 5
                  ports:
                      - containerPort: 5000
                        protocol: TCP
                      - containerPort: 8080
                        protocol: TCP
                  env:
                      - name: REST_API_URL
                        valueFrom:
                            configMapKeyRef:
                                name: plugins-jenkins
                                key: plugins.jenkins.api.url
                      - name: DATA_FILE_URL
                        valueFrom:
                            configMapKeyRef:
                                name: plugins-jenkins
                                key: plugins.jenkins.data.file.url

    # It seems that this pod require quite a lot of resources, so let's wait and see before defining resource limitation
