#!/bin/bash
STORAGE_ACCOUNT_KEY=$(echo -n "$STORAGE_ACCOUNT_KEY" | base64 -w 0)
STORAGE_ACCOUNT_NAME=$(echo -n "$STORAGE_ACCOUNT_NAME" | base64 -w 0)
AZURE_OMS_CUSTOMER_ID=$(echo -n "$AZURE_OMS_CUSTOMER_ID" | base64 -w 0)
STORAGE_ACCOUNT_LOGS_KEY=$(echo -n "$STORAGE_ACCOUNT_LOGS_KEY" | base64 -w 0)
AZURE_ARCHIVE_CONTAINER=$(echo -n "$AZURE_ARCHIVE_CONTAINER" | base64 -w 0 )
AZURE_ARCHIVE_STORAGE_ACCESSKEY=$(echo -n "$STORAGE_ACCOUNT_LOGS_KEY" | base64 -w 0)
DATADOG_API_KEY=$(echo -n "${DATADOG_API_KEY}"| base64)
