---
apiVersion: v1
kind: Service
metadata:
  name: plugins-jenkins
  labels:
    app: plugin-jenkins
    type: plugins-jenkins
    logtype: archive
spec:
  ports:
  - name: frontend
    protocol: TCP
    targetPort: 5000
    port: 5000
  - name: backend
    protocol: TCP
    targetPort: 8080
    port: 8080
  selector:
    type: plugins-jenkins
