=== Definitions
Definitions are common resources to all environments, they are services, daemonsets, pods version,... +
Everything that is not specific to an environment

=== Configuration
Configuration are resources specific to an environment. +
They are complementary with definitions. +
They are secrets or configmaps used to differentiate infrastructure components between environments (dev,staging,production,...). +
Secrets contain hidden key/value available for pods +
Configmaps contain public key/value available for pods +

IMPORTANT: . Secrets files must be encrypted on git and we must use the same gpg key for all encrypted files related to an environment. +
. We can only deploy one environment per cluster at the moment.

=== Systems
Systems are resources that add core features to kubernetes like ingress.
They must be deploy first, as other resources rely on them.

There are two ways to use this project.

Either we use an environment already defined.
It's the easiest scenario where you mainly need kubectl and the public certificate to unencrypt secrets files.

Either we create a new one (or update an existing one). +
It asks more requirements as you gonna have to create configmaps and secrets files then encrypt them with public key. +
You may also need tools to get secrets key/value. +
For example azure-client to retrieve azure disk storage keys.

=== Trash
Trash are ressources that will be remove from cluster. +
At the moment, this is the only way to remove cluster ressources
