ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= K8s: Orchestrator Project

:toc:

== Description
This project deploy and orchestrate jenkins-infra components on a Kubernetes infrastructure. +
It contains three categories of definitions. +
We define them as definitions, configurations and systems.

1. Definitions:

Definitions are common resources to all environments, they are services, daemonsets, pods version,... +
Everything that is not specific to an environment

2. Configuration:

Configuration are resources specific to an environment. +
They are complementary with definitions. +
They are secrets or configmaps use to differentiate infrastructure components between environments (dev,staging,production,...). +
Secret contain hidden key/value available for pods +
Configmap contain public key/value available for pods +

IMPORTANT: . Secrets files must be encrypted on git and we must use the same gpg key for all encrypted files related to an environment. +
. We can only deploy one environment per cluster at the moment.

3. Systems
Systems are resources that add core features to kubernetes like ingress.
They must be deploy first, as other resources rely on them.

There are two ways to use this project.

Either we use an environment already defined.
It's the easiest scenario where you mainly need kubectl and the key to unencrypt secrets files.

Either we create a new one. +
It ask more requirements as you gonna have to create configmaps, and secrets files. +
You will also need all tools to get secrets key/value. +
For example azure-client to retrieve azure disk storage keys.

== Requirements
In order to use this project, you gonna need following tools.

make | gpg | ssh | bats | kubectl

N.B.: +
Some additionals tools can be needed to generate specific secret files. +
They are explains in Variables section

=== Kubectl

In order to apply kubernetes files, you gonna need
'kubectl' installed and correctly configured. +
A version of kubectl is provided in bin folder.
You can use one of the following method to configure it.

===== 1. Ssh (Prefered method)
Require ssh access to kubernetes cluster with user azureuser.

Run: ```make init/kubectl/ssh```

===== 2. Azure Cli
Require azure-cli correctly configured and a ssh access
It may be easier to use the ssh method as you don't need azure-cli

Run: ```make init/kubectl/ssh``` 

== Jenkinsfile
In order to run this project through Jenkins, we need to configure two credentials.

1. An ssh key that have access to azureuser@kubernetes_cluster with credentials_id 'ssh-k8s'
2. A text credential with id 'k8s-vault-password' which contain $VAULT_PASSWORD to decrypt gpg files

IMPORTANT: Environment defined by $ENV will be deploy on ${PREFIX}mgmt.${LOCATION}.cloudapp.azure.com.+
Therefor ensure that ENV, PREFIX, LOCATION correspond to what you need.
Defaults values are defined in k8s.default

== Variables
=== Description
Variables can be define in following places.
! Order matter

1. k8s.cfg
2. Shell environment
3. k8s.default

We have two types of variables, project and secrets.
By project variables, we mean all variables used to run k8s project.
They are mandatory and must be define either in k8s.cfg either in global shell environment.

Secrets variables are used to generate secrets files.
You only need to define them if you want to create a new environment or if you want to update an existing one.

All variables are explained below

.Project
[cols="4"]
|===
| Variables
| Default value
| Mandatory
| Description

| PREFIX
| jenkinsci
| v
| In combination with LOCATION, use to know on which azure cluster we want to deploy/orchestrate k8s project

| LOCATION
| eastus
| v
| In combination with PREFIX, use to know on which azure cluster we want to deploy/orchestrate  k8s project

| ENV
| staging
| v
| Use to define which $ENV we want to deploy/orchestrated.

| VAULT_PASSWORD
| x
| Required if some secrets need to be decrypted
| Use to decrypt gpg secrets files under ./config/$ENV/secrets

|===

.Secrets
[cols="4"]
|===
| Variables
| Default value
| Mandatory
| Description

| AZURE_ARCHIVE_CONTAINER
| k8slogs
| Default value
| Used by fluentd plugins to know on which container send logs

| STORAGE_ACCOUNT_NAME
| Defined by azure-cli
| Not mandatory if azure-cli is working
| Used by k8s to mount shared disk storage

| STORAGE_ACCOUNT_KEY
| Defined by azure-cli
| Not mandatory if azure-cli is working
| Used by k8s to mount shared disk storage

| STORAGE_ACCOUNT_LOGS_KEY
| x
| v (cfr doc folder)
| Used by fluentd-plugin-loganalytics

| AZURE_OMS_CUSTOMER_ID
| Defined by azure-cli
| Not mandatory if azure-cli is working
| Used by fluentd-plugin-loganalytics

| DATADOG_API_KEY
| x
| v
| Used to send collected data to datadog

| DOCKER_REGISTRY_SERVER
| x
| v
| Used to generate docker registry secret file


| DOCKER_USER
| x
| v
| Used to generate docker registry secret file


| DOCKER_PASSWORD
| x
| v
| Used to generate docker registry secret file

| DOCKER_EMAIL
| x
| v
| Used to generate docker registry secret file


|===

Remarks:
This project is a good demonstration of continuous delivery through Jenkins.
