# How to get storage account key 
# PREFIX=<env_prefix defined by terraform plans> 

apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
    # fluent-plugin-azure-loganalytics:
    # Use to configure fluentd plugin
    # ! Don't forget to enable customs logs preview feature as explaine here
    # ../doc/enable_azure_custom_logs.png
   
  azurestorageaccountname: STORAGE_ACCOUNT_NAME
  azurestorageaccountkey: STORAGE_ACCOUNT_KEY

    # Kubernetes: Two following key are used by kubernetes to mount shared disk storage
    # Two next key value can be found following this documenation -> https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-get-started 
    # azurelogsstorageaccountkey == PRIMARY KEY
    # azurelogsanalyticsworkspace == WORKSPACE ID
    # A screenshot is avaible here -> ../doc/get_azure_OMS_credentials.png
  azurelogsstorageaccountkey: STORAGE_ACCOUNT_LOGS_KEY
  azurelogsanalyticsworkspace: AZURE_OMS_CUSTOMER_ID

    # fluent-plugin-azurestorage:
    # Use to configure fluentd-azure-storage plugin
    # which is not use at the moment
    #
  azurearchivestorageaccount: STORAGE_ACCOUNT_NAME
  azurearchivestorageaccesskey: STORAGE_ACCOUNT_KEY
  azurearchivecontainer: AZURE_ARCHIVE_CONTAINER

